import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import Hero from '../components/Hero';
import About from './about';
import Work from './work';
import { projectData } from '../data/projectData';

export default function Home() {

// console.log(projectData)
  return (
    <div>
      <Head>
        <title>Stephen Talley</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading="Stephen Talley" message="Software Engineer"/>
      <About />
      <Work projects={projectData}/>

    </div>
  );
}